name = "test-webauthn"
compatibility_date = "2024-09-13"
compatibility_flags = [ "nodejs_compat" ]

[[kv_namespaces]]
binding = "KV"
id = "**********"
preview_id = "**********"

[[d1_databases]]
binding = "DB"
database_name = "test-webauthn"
database_id = "**********"
preview_database_id = "**********"

[site]
bucket = "./"
